# Generated by Django 3.0.8 on 2020-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_picture',
            field=models.ImageField(default='none', upload_to='profile_pics'),
        ),
    ]
