# Generated by Django 3.1 on 2021-01-16 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
