# Generated by Django 3.1 on 2021-01-17 03:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210116_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
