# Generated by Django 3.1 on 2021-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210121_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
