# Generated by Django 3.0.8 on 2020-09-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_a_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
