# Generated by Django 3.1 on 2021-01-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210121_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='a_image',
        ),
    ]
