# Generated by Django 3.0.8 on 2020-09-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200924_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_author',
            new_name='author',
        ),
    ]
