# Generated by Django 3.0.8 on 2020-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200924_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='a_picture',
        ),
        migrations.AddField(
            model_name='article',
            name='a_image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
