# Generated by Django 3.1 on 2021-01-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_a_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_image',
            field=models.ImageField(default=False, upload_to='profile_pics'),
        ),
    ]
