# Generated by Django 3.1 on 2021-01-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_a_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
