# Generated by Django 3.0.8 on 2020-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200928_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='a_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
