# Generated by Django 3.1.5 on 2021-01-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210122_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='a_image',
        ),
    ]
